version: '3.8'
services:
  app:
    build: .
    command: npm start
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: uzer
      POSTGRES_PASSWORD: pazzword
      POSTGRES_DB: term_project
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"

  redis:
    image: "redis:alpine"
    environment:
      REDIS_PORT: 6379
      REDIS_TTL: 600
    ports:
      - "6379:6379"
